from datetime import datetime, timedelta

from google_auth_oauthlib.flow import InstalledAppFlow

from googleapiclient.discovery import build
import os

SCOPES = [
    "https://www.googleapis.com/auth/calendar"
]

def add_trip_to_calendar(
    source,
    destination,
    travel_date,
    days,
    itinerary
):

    

    BASE_DIR = os.path.dirname(os.path.abspath(__file__))

    CREDENTIALS_PATH = os.path.join(
        BASE_DIR,
        "credentials.json"
    )

    flow = InstalledAppFlow.from_client_secrets_file(
        CREDENTIALS_PATH,
        SCOPES
    )

    creds = flow.run_local_server(
        port=0
    )

    service = build(
        "calendar",
        "v3",
        credentials=creds
    )

    start = datetime.strptime(
        travel_date,
        "%Y-%m-%d"
    )

    end = start + timedelta(
        days=days
    )

    event = {

    "summary": f"✈️ Trip to {destination}",

    "location": destination,

    "description": f"""
AI Travel Planner

Source: {source}

Destination: {destination}

Travel Date: {travel_date}

Duration: {days} Days

--------------------------------------------------

Travel Itinerary

{itinerary}

--------------------------------------------------

Generated by AI Travel Planner
""",

    "start": {
        "date": start.strftime("%Y-%m-%d")
    },

    "end": {
        "date": end.strftime("%Y-%m-%d")
    }

}

    service.events().insert(

        calendarId="primary",

        body=event

    ).execute()

    return True